DRIVER_NAMES = {
    "PIA": "Oscar Piastri",
    "NOR": "Lando Norris",
    "VER": "Max Verstappen",
    "RUS": "George Russell",
    "LEC": "Charles Leclerc",
    "HAM": "Lewis Hamilton",
    "ANT": "Andrea Kimi Antonelli",
    "ALB": "Alex Albon",
    "HAD": "Isack Hadjar",
    "HUL": "Nico Hülkenberg",
    "STR": "Lance Stroll",
    "SAI": "Carlos Sainz",
    "LAW": "Liam Lawson",
    "ALO": "Fernando Alonso",
    "OCO": "Esteban Ocon",
    "GAS": "Pierre Gasly",
    "TSU": "Yuki Tsunoda",
    "BOR": "Gabriel Bortoleto",
    "BEA": "Oliver Bearman",
    "COL": "Franco Colapinto",
}
