DRIVERS = {
    "PIA": {"name": "Oscar Piastri", "team": "McLaren", "color": "#FF8700", "number": 81, "flag": "🇦🇺"},
    "NOR": {"name": "Lando Norris", "team": "McLaren", "color": "#FF8700", "number": 4, "flag": "🇬🇧"},
    "VER": {"name": "Max Verstappen", "team": "Red Bull Racing", "color": "#3671C6", "number": 1, "flag": "🇳🇱"},
    "RUS": {"name": "George Russell", "team": "Mercedes", "color": "#27F4D2", "number": 63, "flag": "🇬🇧"},
    "LEC": {"name": "Charles Leclerc", "team": "Ferrari", "color": "#E8002D", "number": 16, "flag": "🇲🇨"},
    "HAM": {"name": "Lewis Hamilton", "team": "Ferrari", "color": "#E8002D", "number": 44, "flag": "🇬🇧"},
    "ANT": {"name": "Andrea Kimi Antonelli", "team": "Mercedes", "color": "#27F4D2", "number": 12, "flag": "🇮🇹"},
    "ALB": {"name": "Alex Albon", "team": "Williams", "color": "#64C4FF", "number": 23, "flag": "🇹🇭"},
    "HAD": {"name": "Isack Hadjar", "team": "RB", "color": "#6692FF", "number": 37, "flag": "🇫🇷"},
    "HUL": {"name": "Nico Hülkenberg", "team": "Sauber", "color": "#52E252", "number": 27, "flag": "🇩🇪"},
    "STR": {"name": "Lance Stroll", "team": "Aston Martin", "color": "#229971", "number": 18, "flag": "🇨🇦"},
    "SAI": {"name": "Carlos Sainz", "team": "Williams", "color": "#64C4FF", "number": 55, "flag": "🇪🇸"},
    "LAW": {"name": "Liam Lawson", "team": "RB", "color": "#6692FF", "number": 30, "flag": "🇳🇿"},
    "ALO": {"name": "Fernando Alonso", "team": "Aston Martin", "color": "#229971", "number": 14, "flag": "🇪🇸"},
    "OCO": {"name": "Esteban Ocon", "team": "Alpine", "color": "#FF87BC", "number": 31, "flag": "🇫🇷"},
    "GAS": {"name": "Pierre Gasly", "team": "Alpine", "color": "#FF87BC", "number": 10, "flag": "🇫🇷"},
    "TSU": {"name": "Yuki Tsunoda", "team": "RB", "color": "#6692FF", "number": 22, "flag": "🇯🇵"},
    "BOR": {"name": "Gabriel Bortoleto", "team": "Sauber", "color": "#52E252", "number": 8, "flag": "🇧🇷"},
    "BEA": {"name": "Oliver Bearman", "team": "Haas", "color": "#B6B6B8", "number": 50, "flag": "🇬🇧"},
    "COL": {"name": "Franco Colapinto", "team": "Williams", "color": "#64C4FF", "number": 43, "flag": "🇦🇷"},
}

DRIVER_NAMES = {k: v['name'] for k, v in DRIVERS.items()}

ROUND_NAMES_2025 = {
    1: "AUS",
    2: "CHN",
    3: "JPN",
    4: "BHR",
    5: "SAU",
    6: "MIA",
    7: "EMI",
    8: "MON",
    9: "ESP",
    10: "CAN",
    11: "AUT",
    12: "GBR",
    13: "BEL",
    14: "HUN",
    15: "NED",
    16: "ITA",
    17: "AZE",
    18: "SIN",
    19: "USA",
    20: "MXC",
    21: "SAP",
    22: "LVG",
    23: "QAT",
    24: "ABU",
}
